import type { Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import { Inter as FontSans } from 'next/font/google'

import { cn } from '@/lib/utils'
import SiteHeader from '@/components/SiteHeader'
import SiteFooter from '@/components/SiteFooter'

import '@/styles/globals.css'

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans'
})

export const metadata: Metadata = {
  title: 'Next Auth Starter',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className='dark' lang='en'>
      <ClerkProvider>
        <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
          <SiteHeader />
          <main className='relative flex h-full flex-grow flex-col min-h-[calc(100vh-48px)] pt-[48px] sm:min-h-[calc(100vh-100px)] sm:pt-[80px]'>
            {children}
          </main>
          <SiteFooter />
        </body>
      </ClerkProvider>
    </html>
  )
}
